### ISSUE TITLE
id not returned from VPC as expected

### ISSUE THREAD

**Issue by zabullet** [pulumi/pulumi-awsx#1090]
### What happened?

Simple code which you'd expect to return the id of a vpc does not function as expected.

### Example

```
# Create an AWS VPC
vpc = awsx.ec2.Vpc("test")

# Export the name of the VPC
pulumi.export("vpc_id", vpc.id)

# Print the VPC ID to the Pulumi log
pulumi.log.info(f"VPC ID: {vpc.id}")
```

returns

```    
VPC ID: None
```

### Output of `pulumi about`

```
CLI          
Version      3.83.0
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.42.0
awsx    1.0.5
docker  3.6.1
python  unknown

Host
OS       Microsoft Windows 11 Pro
Version  10.0.22621 Build 22621
Arch     x86_64

This project is written in python: executable='C:\Python311\python.exe' version='3.11.5
'

Backend
Name           pulumi.com
URL            https://app.pulumi.com/zabullet
User           zabullet
Organizations  zabullet

Dependencies:
NAME         VERSION
pip          23.2.1
pulumi-awsx  1.0.5
setuptools   68.2.2
wheel        0.41.2

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Zaid-Ajaj** [comment]
Hi there @zabullet, I believe the problem is that is you are using `vpc.id` directly inside a string when it is actually an `Output[str]` so you need to use `apply` to get the value:
```python
vpc.id.apply(lambda id: pulumi.log.info(f"VPC ID: {id}"))
```
can you see if this helps? Also the ID is only available during `pulumi up`, not `pulumi preview`

**Comment by zabullet** [comment]
```    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "C:\work\personal\WaaS\wallet-db\pulumi\__main__.py", line 98, in <module>
        vpc.id.apply(lambda id: pulumi.log.info(f"VPC ID: {id}"))
        ^^^^^^^^^^^^
    AttributeError: 'NoneType' object has no attribute 'apply'
```

**Comment by zabullet** [comment]
```    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "C:\<redacted>\pulumi\__main__.py", line 98, in <module>
        vpc.id.apply(lambda id: pulumi.log.info(f"VPC ID: {id}"))
        ^^^^^^^^^^^^
    AttributeError: 'NoneType' object has no attribute 'apply'
```

**Comment by zabullet** [comment]
nvm. It needs to be vpc_id, not just .id
