### ISSUE TITLE
SIGSEGV on ECS Service alarms

### ISSUE THREAD

**Issue by kema-dev** [pulumi/pulumi-awsx#1147]
### What happened?

I got an ECS cluster, provisioned using Pulumi, no problem so far.
However, I get a `SIGSEGV` when trying to add alarms to it.

### Example

```ts
const fargateService = new awsx.ecs.FargateService(
  fargateServiceName,
  {
    name: <service_name>,
    cluster: <cluster_arn>,
    taskDefinition: <taskdef_arn>,
	[...]
    alarms: {
      enable: <true / false>,
      rollback: <true / false>,
      alarmNames: [<whaterver "string", even nothing>],
    },
	[...]
  }
);
```

### Output of `pulumi about`

```log
CLI
Version      3.91.1
Go Version   go1.21.3
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.42.0
aws         5.42.0
aws-native  0.80.0
aws-native  0.80.0
awsx        1.0.6
awsx        1.0.5
docker      3.6.1
docker      3.6.1
nodejs      unknown
random      4.14.0
random      4.14.0

Host
OS       fedora
Version  38
Arch     x86_64

This project is written in nodejs: executable='/home/linuxbrew/.linuxbrew/bin/node' version='v21.1.0'

Current Stack: REDACTED/REDACTED/REDACTED

TYPE                                               URN
pulumi:pulumi:Stack                                urn:pulumi:REDACTED::REDACTED::pulumi:pulumi:Stack::REDACTED-REDACTED
pulumi:providers:pulumi                            urn:pulumi:REDACTED::REDACTED::pulumi:providers:pulumi::default
pulumi:pulumi:StackReference                       urn:pulumi:REDACTED::REDACTED::pulumi:pulumi:StackReference::REDACTED/REDACTED/REDACTED
pulumi:providers:random                            urn:pulumi:REDACTED::REDACTED::pulumi:providers:random::default_4_14_0
pulumi:providers:aws                               urn:pulumi:REDACTED::REDACTED::pulumi:providers:aws::default_5_42_0
random:index/randomPassword:RandomPassword         urn:pulumi:REDACTED::REDACTED::random:index/randomPassword:RandomPassword::REDACTED
aws:secretsmanager/secret:Secret                   urn:pulumi:REDACTED::REDACTED::aws:secretsmanager/secret:Secret::REDACTED
aws:efs/fileSystem:FileSystem                      urn:pulumi:REDACTED::REDACTED::aws:efs/fileSystem:FileSystem::REDACTED
aws:iam/policy:Policy                              urn:pulumi:REDACTED::REDACTED::aws:iam/policy:Policy::REDACTED
random:index/randomPassword:RandomPassword         urn:pulumi:REDACTED::REDACTED::random:index/randomPassword:RandomPassword::REDACTED
aws:secretsmanager/secret:Secret                   urn:pulumi:REDACTED::REDACTED::aws:secretsmanager/secret:Secret::REDACTED
aws:lb/targetGroup:TargetGroup                     urn:pulumi:REDACTED::REDACTED::aws:lb/targetGroup:TargetGroup::REDACTED
aws:iam/role:Role                                  urn:pulumi:REDACTED::REDACTED::aws:iam/role:Role::REDACTED
aws:efs/mountTarget:MountTarget                    urn:pulumi:REDACTED::REDACTED::aws:efs/mountTarget:MountTarget::REDACTED
aws:efs/mountTarget:MountTarget                    urn:pulumi:REDACTED::REDACTED::aws:efs/mountTarget:MountTarget::REDACTED
aws:efs/mountTarget:MountTarget                    urn:pulumi:REDACTED::REDACTED::aws:efs/mountTarget:MountTarget::REDACTED
aws:secretsmanager/secretVersion:SecretVersion     urn:pulumi:REDACTED::REDACTED::aws:secretsmanager/secretVersion:SecretVersion::REDACTED
aws:secretsmanager/secretVersion:SecretVersion     urn:pulumi:REDACTED::REDACTED::aws:secretsmanager/secretVersion:SecretVersion::REDACTED
aws:lb/listenerRule:ListenerRule                   urn:pulumi:REDACTED::REDACTED::aws:lb/listenerRule:ListenerRule::REDACTED
aws:cloudwatch/metricAlarm:MetricAlarm             urn:pulumi:REDACTED::REDACTED::aws:cloudwatch/metricAlarm:MetricAlarm::REDACTED
aws:iam/rolePolicyAttachment:RolePolicyAttachment  urn:pulumi:REDACTED::REDACTED::aws:iam/rolePolicyAttachment:RolePolicyAttachment::REDACTED
aws:iam/rolePolicyAttachment:RolePolicyAttachment  urn:pulumi:REDACTED::REDACTED::aws:iam/rolePolicyAttachment:RolePolicyAttachment::REDACTED
pulumi:providers:awsx                              urn:pulumi:REDACTED::REDACTED::pulumi:providers:awsx::default_1_0_5
awsx:ecs:FargateTaskDefinition                     urn:pulumi:REDACTED::REDACTED::awsx:ecs:FargateTaskDefinition::REDACTED
pulumi:providers:aws                               urn:pulumi:REDACTED::REDACTED::pulumi:providers:aws::default_5_35_0
aws:cloudwatch/logGroup:LogGroup                   urn:pulumi:REDACTED::REDACTED::awsx:ecs:FargateTaskDefinition$aws:cloudwatch/logGroup:LogGroup::REDACTED
aws:ecs/taskDefinition:TaskDefinition              urn:pulumi:REDACTED::REDACTED::awsx:ecs:FargateTaskDefinition$aws:ecs/taskDefinition:TaskDefinition::REDACTED
awsx:ecs:FargateService                            urn:pulumi:REDACTED::REDACTED::awsx:ecs:FargateService::REDACTED
aws:ecs/service:Service                            urn:pulumi:REDACTED::REDACTED::awsx:ecs:FargateService$aws:ecs/service:Service::REDACTED


Found no pending operations associated with REDACTED

Backend
Name           pulumi.com
URL            https://app.pulumi.com/REDACTED
User           REDACTED
Organizations  REDACTED, REDACTED
Token type     personal

Dependencies:
NAME                VERSION
ts-node             10.9.1
@pulumi/aws-native  0.80.0
@pulumi/aws         5.42.0
@pulumi/awsx        1.0.5
@pulumi/pulumi      3.81.0
@pulumi/random      4.14.0
@types/node         16.18.48

Pulumi locates its logs in /tmp by default
```

### Additional context

I got no problem if I comment out the alarms section.

Here is what looks like the associated stack trace :

```log
Diagnostics:
  pulumi:pulumi:Stack (REDACTED):
    error: update failed

    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x92be403]
    goroutine 122 [running]:
    github.com/hashicorp/terraform-provider-aws/internal/service/ecs.resourceServiceUpdate({0xee7d5e8?, 0xc003d30f00}, 0xc003b2af80, {0xd892220?, 0xc0004b2c00})
        /home/runner/work/pulumi-aws/pulumi-aws/upstream/internal/service/ecs/service.go:872 +0xd63
    github.com/hashicorp/terraform-provider-aws/internal/provider.interceptedHandler[...].func1(0xbbea460?, {0xd892220?, 0xc0004b2c00?})
        /home/runner/work/pulumi-aws/pulumi-aws/upstream/internal/provider/intercept.go:94 +0x175
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xee7d578?, {0xee7d578?, 0xc0001aa008?}, 0xd?, {0xd892220?, 0xc0004b2c00?})
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20220824175045-450992f2f5b9/helper/schema/resource.go:741 +0x87
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0013b10a0, {0xee7d578, 0xc0001aa008}, 0xc003cb7ee0, 0xc003b2a700, {0xd892220, 0xc0004b2c00})
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20220824175045-450992f2f5b9/helper/schema/resource.go:852 +0x83a
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.Apply({0xc000480960?, {0x0?, 0x0?, 0xc003487530?}}, {0xd916f17, 0xf}, {0xee7ec70?, 0xc003af43f0}, {0xee8dcc8, 0xc003b2a700})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.43.0/pkg/tfshim/sdk-v2/provider.go:100 +0x19b
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Update(0xc002fc6780, {0xee7d5e8?, 0xc003aae900?}, 0xc0037e5700)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.43.0/pkg/tfbridge/provider.go:1081 +0x86f
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Update_Handler.func1({0xee7d5e8, 0xc003aae900}, {0xd3aafc0?, 0xc0037e5700})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.59.0/proto/go/provider_grpc.pb.go:609 +0x7b
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0xee7d5e8, 0xc003aae180}, {0xd3aafc0, 0xc0037e5700}, 0xc003a4f2a0, 0xc0039f54b8)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3f9
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Update_Handler({0xd71d900?, 0xc002fc6780}, {0xee7d5e8, 0xc003aae180}, 0xc002de4cb0, 0xc002fa7f20)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.59.0/proto/go/provider_grpc.pb.go:611 +0x138
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc000914000, {0xee8e800, 0xc00313e1a0}, 0xc003a9a900, 0xc0030d4ab0, 0x1770c370, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
    google.golang.org/grpc.(*Server).handleStream(0xc000914000, {0xee8e800, 0xc00313e1a0}, 0xc003a9a900, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
    google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:965 +0x98
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

    The Pulumi runtime detected that 114 promises were still active
    at the time that the process exited. There are a few ways that this can occur:
      * Not using `await` or `.then` on a Promise returned from a Pulumi API
      * Introducing a cyclic dependency between two Pulumi Resources
      * A bug in the Pulumi Runtime
    Leaving promises active is probably not what you want. If you are unsure about
    why you are seeing this message, re-run your program with the `PULUMI_DEBUG_PROMISE_LEAKS`
    environment variable. The Pulumi runtime will then print out additional
    debug information about the leaked promises.

  aws:ecs:Service (REDACTED):
    error: error reading from server: EOF
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
This looks like this upstream issue: https://github.com/hashicorp/terraform-provider-aws/issues/31443

You would need to update to pulumi-aws 6.x, and for that you need to update to awsx 2.x. I hope this helps!

**Comment by kema-dev** [comment]
Ho you're right ! I did not find this issue when I searched for it. I updated `@pulumi/pulumi` `@pulumi/aws` and `@pulumi/awsx` to latest versions, everything works like a charm now.
Thank you !
