### ISSUE TITLE
Build is failing in Travis

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-awsx#462]
Build has been failing in Travis for several days.  Appears to be a TypeScript issue (perhaps newer version of TS got stricter?):

https://travis-ci.com/pulumi/pulumi-awsx/builds/140337312

```
[ wsx/nodejs/examples/dashboards ]     error: Running program '/tmp/p-it-travis-job-dashboards-ac88c3f1-288703320' failed with an unhandled exception:
[ wsx/nodejs/examples/dashboards ]     TSError: ⨯ Unable to compile TypeScript:
[ wsx/nodejs/examples/dashboards ]     index.ts(69,67): error TS2769: No overload matches this call.
[ wsx/nodejs/examples/dashboards ]       Overload 1 of 2, '(args: HorizontalAnnotationArgs): HorizontalAnnotation', gave the following error.
[ wsx/nodejs/examples/dashboards ]         Argument of type 'MetricAlarm' is not assignable to parameter of type 'HorizontalAnnotationArgs'.
[ wsx/nodejs/examples/dashboards ]           Property 'aboveEdge' is missing in type 'MetricAlarm' but required in type 'HorizontalAnnotationArgs'.
[ wsx/nodejs/examples/dashboards ]       Overload 2 of 2, '(args: HorizontalAlarmAnnotationArgs): HorizontalAnnotation', gave the following error.
[ wsx/nodejs/examples/dashboards ]         Argument of type 'MetricAlarm' is not assignable to parameter of type 'HorizontalAlarmAnnotationArgs'.
[ wsx/nodejs/examples/dashboards ]           Types of property 'threshold' are incompatible.
[ wsx/nodejs/examples/dashboards ]             Type 'Output<number | undefined>' is not assignable to type 'Input<number>'.
[ wsx/nodejs/examples/dashboards ]               Type 'OutputInstance<number | undefined> & LiftedObject<undefined, never>' is not assignable to type 'Input<number>'.
[ wsx/nodejs/examples/dashboards ]                 Type 'OutputInstance<number | undefined> & LiftedObject<undefined, never>' is not assignable to type 'OutputInstance<number>'.
[ wsx/nodejs/examples/dashboards ]                   Types of property 'apply' are incompatible.
[ wsx/nodejs/examples/dashboards ]                     Type '{ <U>(func: (t: number | undefined) => Promise<U>): Output<U>; <U>(func: (t: number | undefined) => OutputInstance<U>): Output<U>; <U>(func: (t: number | undefined) => U): Output<U>; }' is not assignable to type '{ <U>(func: (t: number) => Promise<U>): Output<U>; <U>(func: (t: number) => OutputInstance<U>): Output<U>; <U>(func: (t: number) => U): Output<U>; }'.
[ wsx/nodejs/examples/dashboards ]                       Types of parameters 'func' and 'func' are incompatible.
[ wsx/nodejs/examples/dashboards ]                         Types of parameters 't' and 't' are incompatible.
[ wsx/nodejs/examples/dashboards ]                           Type 'number | undefined' is not assignable to type 'number'.
[ wsx/nodejs/examples/dashboards ]                             Type 'undefined' is not assignable to type 'number'.
[ wsx/nodejs/examples/dashboards ]     
[ wsx/nodejs/examples/dashboards ]         at createTSError (/tmp/p-it-travis-job-dashboards-ac88c3f1-288703320/node_modules/ts-node/src/index.ts:261:12)
[ wsx/nodejs/examples/dashboards ]         at getOutput (/tmp/p-it-travis-job-dashboards-ac88c3f1-288703320/node_modules/ts-node/src/index.ts:367:40)
[ wsx/nodejs/examples/dashboards ]         at Object.compile (/tmp/p-it-travis-job-dashboards-ac88c3f1-288703320/node_modules/ts-node/src/index.ts:558:11)
[ wsx/nodejs/examples/dashboards ]         at Module.m._compile (/tmp/p-it-travis-job-dashboards-ac88c3f1-288703320/node_modules/ts-node/src/index.ts:439:43)
[ wsx/nodejs/examples/dashboards ]         at Module._extensions..js (module.js:663:10)
[ wsx/nodejs/examples/dashboards ]         at Object.require.extensions.(anonymous function) [as .ts] (/tmp/p-it-travis-job-dashboards-ac88c3f1-288703320/node_modules/ts-node/src/index.ts:442:12)
[ wsx/nodejs/examples/dashboards ]         at Module.load (module.js:565:32)
[ wsx/nodejs/examples/dashboards ]         at tryModuleLoad (module.js:505:12)
[ wsx/nodejs/examples/dashboards ]         at Function.Module._load (module.js:497:3)
[ wsx/nodejs/examples/dashboards ]         at Module.require (module.js:596:17)
[ wsx/nodejs/examples/dashboards ]  
```

**Comment by CyrusNajmabadi** [comment]
I believe this is actually because the typing for this aws type changed.  The property .threshold changed from `number` to `number | undefined`.  I have a fix for this which i can get in tomorrow.
