### ISSUE TITLE
RunTaskRequest interface usage

### ISSUE THREAD

**Issue by dmkonst** [pulumi/pulumi-awsx#547]
Hello
I'm realtively new to pulumi and have one project where I need to run a specific task inside ECS ( not a Service )
I've read the documentation and found this in API reference https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/awsx/ecs/#RunTaskRequest and to be more detailed I've found this source code https://github.com/pulumi/pulumi-awsx/blob/master/nodejs/awsx/ecs/taskDefinition.ts#L162 but I cannot come up with understanding how do I implement the interface to run the task
Can someone provide an example ? Thanks

**Comment by leezen** [comment]
Are you looking for https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/awsx/ecs/#TaskDefinition-run or do you mean something else?

**Comment by dmkonst** [comment]
Thanks @leezen I've found that already, and was trying to execute the run in such way:

`const runTask = await myTaskDefinition.run({ cluster });`
Where cluster and myTaskDefinition are already specified and created properly by pulumi, but I keep getting the errors like so:

```
error: Running program '/pulumi/main-infrastructure' failed with an unhandled exception:
Error: Cannot call '.get' during update or preview.
To manipulate the value of this Output, use '.apply' instead.
    at Proxy.get (/pulumi/node_modules/@pulumi/pulumi/output.js:172:15)
    at FargateTaskDefinition.run (/pulumi/node_modules/@pulumi/ecs/taskDefinition.ts:226:39)
    at /pulumi/main-infrastructure/index.ts:127:15
    at Generator.next (<anonymous>)
    at fulfilled (/pulumi/main-infrastructure/index.ts:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: update failed
```

And I'm not sure what can be the reason.

**Comment by dmkonst** [comment]
To be more detailed, I found that my task is fargate, so I'm required to specify network configuration. So I came up with something like:

```
    const runTask = await myTaskDefinition.run({ 
        cluster: cluster,
        networkConfiguration: {
            awsvpcConfiguration: {
                subnets: ["subnet-11111111"],
                securityGroups: ["sg-2222222"]
            }
        },
        platformVersion: "1.4.0"
    });
```

But I continue getting same `cannot call .get during update or preview.` which looks like indicates that some issue appeared when pulumi tried to create the task, but it's not clear what issue that is

**Comment by dmkonst** [comment]
@leezen do you have any suggestion ?

**Comment by leezen** [comment]
Sorry, I thought I had replied but somehow I must not have hit 'Comment'. The `run` needs to happen in a context not within the program execution itself. Typically, we would expect it to happen in a Lambda. As the documentation notes, "This API is designed for use at runtime." Here's an example of that: https://www.pulumi.com/docs/guides/crosswalk/aws/ecs/#running-fire-and-forget-tasks -- you can see the `run` is being invoked within the callback for the `eventHandler`

**Comment by vberlier** [comment]
I have a similar issue with this. I'd really like to be able to run a one-off task during the deployment process for running database migrations but since the `.run` method is only usable at "runtime" (inline lambdas) there's no real way of accomplishing this https://github.com/pulumi/pulumi/issues/5083

**Comment by glenfordwilliams** [comment]
@vberlier found a work around? I'm currently in the same position wanting to decouple migrations .
