### ISSUE TITLE
ECS - FargateTaskDefinition - Error when try to run

### ISSUE THREAD

**Issue by alvarogomes** [pulumi/pulumi-awsx#549]
Hey everyone,
I'm using Pulumi to create some infra automation and need to run some task definitions in ECS to access EFS and put some files.
Based on the example in the documentation: https://www.pulumi.com/docs/guides/crosswalk/aws/ecs/#running-fire-and-forget-tasks

I try to do the same following this documentation:
https://www.pulumi.com/docs/reference/pkg/aws/ecs/taskdefinition/
https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/awsx/ecs/#TaskDefinition-run

And the first thing that I saw is in AWS that's just possible using Fargate 1.4.0 and not the 1.3.0
https://aws.amazon.com/blogs/containers/aws-fargate-launches-platform-version-1-4/

But when I try to execute the test I had this error return:

```
error: Running program '/pulumi/main-infrastructure' failed with an unhandled exception:
Error: Cannot call '.get' during update or preview.
To manipulate the value of this Output, use '.apply' instead.
    at Proxy.get (/pulumi/node_modules/@pulumi/pulumi/output.js:172:15)
    at FargateTaskDefinition.run (/pulumi/node_modules/@pulumi/ecs/taskDefinition.ts:226:39)
    at /pulumi/main-infrastructure/index.ts:127:15
    at Generator.next (<anonymous>)
    at fulfilled (/pulumi/main-infrastructure/index.ts:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: update failed
```

That's an example of the code that I'm using.

```
 // this is a docker that will create directories and copy some files to EFS.
  const kafkaTask = new awsx.ecs.FargateTaskDefinition("kafka-task-efs", {
         vpc:vpcSelected,
         containers: {
             kafkaTask: {
                 image: imageKafkaTaskEfs,
                 logConfiguration: {
                     logDriver: "awslogs",
                     options: {
                         "awslogs-group": "ecs-kafka",
                         "awslogs-region": "eu-central-1",
                         "awslogs-stream-prefix": "kafka-task-efs"
                     }
                 },
                 mountPoints: [
                     {containerPath: "/mnt/data", sourceVolume: "kafka-data-efs"}
                 ]
             }
         },
         volumes: [
             {name: "kafka-data-efs", efsVolumeConfiguration: {rootDirectory: "/", fileSystemId: fsKafka.id}}
         ]
     });
    //Run the Task...
     const prepareEfs = await kafkaTask.run({
         cluster: cluster,
         platformVersion: "1.4.0"
     });
```

I think is some error in the execution of this procedure on AWS, but in the same time can be a Pulumi bugfix because not enable the user to see the error.

Does anyone have idea what's going on in this case?

Thanks :)

**Comment by leezen** [comment]
That `run` is meant to be outside of the Pulumi program itself. Typically, you would have that run exist in a callback function, similar to in the example on the page you linked (https://www.pulumi.com/docs/guides/crosswalk/aws/ecs/#running-fire-and-forget-tasks). You'll see in that example, the run happens in a Lambda handler. The `.get` will only work after the function is serialized and being executed outside of the pulumi program context.
