### ISSUE TITLE
"Vpc.vpc" property broken?

### ISSUE THREAD

**Issue by mdhornet90** [pulumi/pulumi-awsx#561]
I'm trying to add an ingress rule to my (custom) VPC's `defaultSecurityGroupId`, using the following declarations:
```
const vpc = new awsx.ec2.Vpc('custom-vpc', {
  tags: { Name: 'Custom VPC' },
  numberOfAvailabilityZones: 1,
  subnets: [{ type: 'public', tags: { Name: 'Custom Subnet' } }],
  enableDnsHostnames: false,
});

const defaultSecurityGroupId = vpc.vpc.apply(vpc => vpc.defaultSecurityGroupId); // Appears to fail here

awsx.ec2.SecurityGroup.fromExistingId(
  'default',
  defaultSecurityGroupId,
).createIngressRule('ssh-access', {
  location: new awsx.ec2.AnyIPv4Location(),
  ports: new awsx.ec2.TcpPorts(22),
  description: 'SSH Access',
});
```

And I encounter the following error every time, whether I'm updating an existing stack or creating a brand new one:
```
Diagnostics:
  pulumi:pulumi:Stack (project):
    error: Running program '/Users/chrismurphy/programming/side_projects/alerts/infrastructure' failed with an unhandled exception:
    Error: invocation of aws:ec2/getVpc:getVpc returned an error: invoking aws:ec2/getVpc:getVpc: no matching VPC found
        at monitor.invoke (/Users/chrismurphy/programming/side_projects/alerts/infrastructure/node_modules/@pulumi/pulumi/runtime/invoke.js:136:33)
        at Http2CallStream.call.on (/Users/chrismurphy/programming/side_projects/alerts/infrastructure/node_modules/@grpc/grpc-js/src/client.ts:155:9)
        at Http2CallStream.emit (events.js:203:15)
        at process.nextTick (/Users/chrismurphy/programming/side_projects/alerts/infrastructure/node_modules/@grpc/grpc-js/src/call-stream.ts:186:14)
        at process._tickCallback (internal/process/next_tick.js:61:11)
 ...
```

Is there something I'm missing trying to use this property? I understand it's an `Output<Vpc>` but using `apply` also fails me.

EDIT: updated retrieval of `defaultSecurityGroupId` to reflect chained output values

**Comment by mdhornet90** [comment]
I figured it out:
```
const vpc = new awsx.ec2.Vpc('beer-alerts-vpc', {
  tags: { Name: 'Beer Alerts VPC' },
  numberOfAvailabilityZones: 1,
  subnets: [{ type: 'public', tags: { Name: 'Beer Alerts Subnet' } }],
  enableDnsHostnames: false,
});

new awsx.ec2.SecurityGroup('default', { vpc }).createIngressRule('ssh-access', {
  location: new awsx.ec2.AnyIPv4Location(),
  ports: new awsx.ec2.TcpPorts(22),
  description: 'SSH Access',
});
```

This was based on perusing the awsx/securityGroup source code and finding [this line](https://github.com/pulumi/pulumi-awsx/blob/ac937595322bf1560b67598a612b4374253cd6aa/nodejs/awsx/ec2/securityGroup.ts#L50).

Had to modify the above code accordingly:
```
const vpc = new awsx.ec2.Vpc('beer-alerts-vpc', {
  tags: { Name: 'Beer Alerts VPC' },
  numberOfAvailabilityZones: 1,
  subnets: [{ type: 'public', tags: { Name: 'Beer Alerts Subnet' } }],
  enableDnsHostnames: false,
});

new awsx.ec2.SecurityGroup('default', { vpc }).createIngressRule('ssh-access', {
  location: new awsx.ec2.AnyIPv4Location(),
  ports: new awsx.ec2.TcpPorts(22),
  description: 'SSH Access',
});
```

Imo, it's surprising and a little silly that a full `awsx.Vpc` needs to be passed in as a filter property, especially when it has a higher precedence than the id of a `SecurityGroup`, maybe this is an opportunity for a docs improvement?

**Comment by lukehoban** [comment]
Glad to hear you found a solution here. Definitely an opportunity for docs and or api design improvements.
