### ISSUE TITLE
[awsx:Apigateway] Promise leak detected when I create object in component Resource

### ISSUE THREAD

**Issue by MatiasNMont** [pulumi/pulumi-awsx#652]
Hi!! I have a Promise leak ... my code is 
```
import * as aws from '@pulumi/aws';
import {RouteState} from '@pulumi/aws/apigatewayv2';
import * as awsx from '@pulumi/awsx';
/* Example import if needed
import * as cloud from '@pulumi/cloud-aws';
import {Container} from '@pulumi/cloud';
*/
import * as pulumi from '@pulumi/pulumi';
import {ResourceOptions} from '@pulumi/pulumi';
import {debug, info} from '@pulumi/pulumi/log';
import {merge} from 'lodash';
import * as path from 'path';


enum apiKeySourceEnum {
    authorizer = 'AUTHORIZER',
    header = 'HEADER',
}

interface routes {
    path:string,
    method?:awsx.apigateway.Method,
    eventHandler?: aws.lambda.Function,
    localPath?:string,
    contentType?: string,
    index?: boolean | string,
    target?:any,
    data?: any,
}
export interface apiGatewayArgs{
    name:string,
    routes: routes[],
    lambda: pulumi.Output<aws.lambda.Function>,
    apiKeySource?: string,
    swaggerString?: string,
    stageName?:string,
    lambdaConfig?:string,
}
/* your specific component name */
export class ApiGategayComponent extends pulumi.ComponentResource {
    public readonly instance: pulumi.Output<awsx.apigateway.API>;
    public readonly arn: pulumi.Output<string | undefined>;
    public readonly id: pulumi.Output<string | undefined>;

    /** @internal */
    public static readonly componentId = 'pkg:awsx:apiGateway';
    public static readonly packageInfo = require('../package.json');
    public static readonly packageInfoCaller = require(path.join(process.cwd(), 'package.json'));

    constructor(name: string, args: apiGatewayArgs, opts?: any) {
        super(ApiGategayComponent.componentId, name, {}, opts);

        
        debug('[ ** ] Ejecutando Api Gateway ');
        
        const routesAux = this.generateRoutes(args.routes,args.lambda);
        debug(`[ ** ] ROUTES: ${ routesAux }`);
        const instance = new awsx.apigateway.API(args.name, {
            routes: routesAux,
            apiKeySource: (args.apiKeySource?.toUpperCase()==apiKeySourceEnum.authorizer)?apiKeySourceEnum.authorizer:apiKeySourceEnum.header,
        }, opts);
        (instance as any).id = instance;
  

        this.instance = pulumi.output(instance);
        this.arn = pulumi.output((instance as any).arn);
        this.id = pulumi.output((instance as any).id);

        this.registerOutputs();
    }
     generateRoutes(routes:routes[], lambda: pulumi.Output<aws.lambda.Function>):awsx.apigateway.Route[]{
        const routeArray:any[] = [];
        for (let index=0; index < routes.length; index++) {
            if (routes[index].path && routes[index].method && !routes[index].data) {
                debug('·········· SETTING EVENTHANDLER TYPE ROUTE ·········');
                debug(`[ ** ]Routes: ${ routes[index].path } \n[ ** ]Method: ${ routes[index].method }`);
                const methodAux =<awsx.apigateway.Method> routes[index].method;

                pulumi.all([lambda]).apply(([lambda])=>{
                    const item: awsx.apigateway.EventHandlerRoute = {
                        path: routes[index].path,
                        method: methodAux,
                        eventHandler: lambda,
                    }
                    routeArray.push(item);
                });                
             } 
        }
        return <awsx.apigateway.Route[]> routeArray;
    }
}
```
I need the api to use the lambda function passed by argument, but when I run this I receive next message: 

```
Promise leak detected:
    CONTEXT(788): resolveURN(resource:api-gateway-test[aws:apigateway:x:API])
    STACK_TRACE:
    Error
        at Object.debuggablePromise (/home/appsadm/repos/pulumi_component/mycomponent-aws-api-gateway/node_modules/@pulumi/pulumi/runtime/debuggable.js:69:75)
        at /home/appsadm/repos/pulumi_component/mycomponent-aws-api-gateway/node_modules/@pulumi/pulumi/runtime/resource.js:339:61
        at Generator.next (<anonymous>)
        at /home/appsadm/repos/pulumi_component/mycomponent-aws-api-gateway/node_modules/@pulumi/pulumi/runtime/resource.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/home/appsadm/repos/pulumi_component/mycomponent-aws-api-gateway/node_modules/@pulumi/pulumi/runtime/resource.js:17:12)
        at prepareResource (/home/appsadm/repos/pulumi_component/mycomponent-aws-api-gateway/node_modules/@pulumi/pulumi/runtime/resource.js:331:12)
        at Object.registerResource (/home/appsadm/repos/pulumi_component/mycomponent-aws-api-gateway/node_modules/@pulumi/pulumi/runtime/resource.js:213:24)
        at new Resource (/home/appsadm/repos/pulumi_component/mycomponent-aws-api-gateway/node_modules/@pulumi/pulumi/resource.js:215:24)
        at new ComponentResource (/home/appsadm/repos/pulumi_component/mycomponent-aws-api-gateway/node_modules/@pulumi/pulumi/resource.js:386:9)
```
    Promise leak detected:
    CONTEXT(789): resolveURNIsKnown(resource:api-gateway-test[aws:apigateway:x:API])
    STACK_TRACE:
    Error
        at Object.debuggablePromise (/home/appsadm/repos/pulumi_component/mycomponent-aws-api-gateway/node_modules/@pulumi/pulumi/runtime/debuggable.js:69:75)
        at /home/appsadm/repos/pulumi_component/mycomponent-aws-api-gateway/node_modules/@pulumi/pulumi/runtime/resource.js:339:165
        at Generator.next (<anonymous>)
        at /home/appsadm/repos/pulumi_component/mycomponent-aws-api-gateway/node_modules/@pulumi/pulumi/runtime/resource.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/home/appsadm/repos/pulumi_component/mycomponent-aws-api-gateway/node_modules/@pulumi/pulumi/runtime/resource.js:17:12)
        at prepareResource (/home/appsadm/repos/pulumi_component/mycomponent-aws-api-gateway/node_modules/@pulumi/pulumi/runtime/resource.js:331:12)
        at Object.registerResource (/home/appsadm/repos/pulumi_component/mycomponent-aws-api-gateway/node_modules/@pulumi/pulumi/runtime/resource.js:213:24)
        at new Resource (/home/appsadm/repos/pulumi_component/mycomponent-aws-api-gateway/node_modules/@pulumi/pulumi/resource.js:215:24)
        at new ComponentResource (/home/appsadm/repos/pulumi_component/mycomponent-aws-api-gateway/node_modules/@pulumi/pulumi/resource.js:386:9)

I would like to understand what is generating several Promise Leak... 

Thanks

**Comment by MatiasNMont** [comment]
Close this issues because it was fixed adding dependency instance output.
