### ISSUE TITLE
makeLogGroupId doesn't use custom provider

### ISSUE THREAD

**Issue by titanous** [pulumi/pulumi-awsx#875]
### What happened?

```
    Error: failed to register new resource backend-primary [awsx:ecs:FargateTaskDefinition]: 2 UNKNOWN: Invoke: Default provider for 'aws' disabled. 'aws:index/getCallerIdentity:getCallerIdentity' must use an explicit provider.
        at Object.registerResource (/workspaces/kolrami/infra/backend/node_modules/@pulumi/runtime/resource.ts:292:27)
        at new Resource (/workspaces/kolrami/infra/backend/node_modules/@pulumi/resource.ts:400:13)
        at new ComponentResource (/workspaces/kolrami/infra/backend/node_modules/@pulumi/resource.ts:888:9)
        at new FargateTaskDefinition (/workspaces/kolrami/infra/backend/node_modules/@pulumi/ecs/fargateTaskDefinition.ts:90:9)
        at Object.<anonymous> (/workspaces/kolrami/infra/backend/index.ts:24:24)
        at Module._compile (node:internal/modules/cjs/loader:1103:14)
        at Module.m._compile (/workspaces/kolrami/infra/backend/node_modules/ts-node/src/index.ts:439:23)
        at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
        at Object.require.extensions.<computed> [as .ts] (/workspaces/kolrami/infra/backend/node_modules/ts-node/src/index.ts:442:12)
        at Module.load (node:internal/modules/cjs/loader:981:32)
    error: Error: Invoke: Default provider for 'aws' disabled. 'aws:index/getCallerIdentity:getCallerIdentity' must use an explicit provider.
        at Object.callback (/snapshot/awsx/node_modules/@pulumi/pulumi/runtime/invoke.js:141:33)
        at Object.onReceiveStatus (/snapshot/awsx/node_modules/@grpc/grpc-js/src/client.ts:338:26)
        at Object.onReceiveStatus (/snapshot/awsx/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
        at Object.onReceiveStatus (/snapshot/awsx/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
        at /snapshot/awsx/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
        at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

### Steps to reproduce

Create an `awsx.ecs.FargateTaskDefinition` with the default `aws` provider disabled and a custom provider specified:

```yaml
config:
  pulumi:disable-default-providers:
    - aws
```

### Expected Behavior

All internal calls use the custom provider.

### Actual Behavior

There's a `getCallerIdentity` call that uses the default provider: https://github.com/pulumi/pulumi-awsx/blob/0327b8d0384587da89e6f879431e405045b87f46/awsx/cloudwatch/logGroup.ts#L123

### Versions used

```
CLI          
Version      3.35.3
Go Version   go1.17.11
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.9.2
awsx    1.0.0-beta.9
docker  3.2.0
nodejs  unknown

Host     
OS       ubuntu
Version  20.04
Arch     x86_64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by daniel-westerfeld** [comment]
I am getting the same error using `awsx.ecs.FargateService` with Python as runtime. Here a workaround is creating an `aws.cloudwatch.LogGroup` and passing it to the TaskDefinition via the "[log_group](https://www.pulumi.com/registry/packages/awsx/api-docs/ecs/fargatetaskdefinition/#defaultloggroup)" argument. However, I think this bug should still be fixed since with this solution we can't enjoy the whole comfort of awsx.

**Comment by corymhall** [comment]
It looks like this has been fixed. If anyone is still seeing this issue let me know.
