### ISSUE TITLE
Cannot create awsx.ec2.Vpc with `assume_role` for provider

### ISSUE THREAD

**Issue by chris-stetter** [pulumi/pulumi-awsx#961]
### What happened?

Hi, I am trying to deploy a VPC with `pulumi-awsx` to a newly created account using `assume_role` for the provider.

### Steps to reproduce

```
import pulumi
import pulumi_aws as aws
import pulumi_awsx as awsx

config: dict = {
    "skip_credentials_validation": True,
    "skip_metadata_api_check": False,
}

org_provider = aws.Provider("org-provider", **config)

account = aws.organizations.Account(
    "account", email="test@example.com", role_name="account-role", opts=pulumi.ResourceOptions(provider=org_provider)
)

provider = aws.Provider(
    "account-provider",
    assume_role=aws.ProviderAssumeRoleArgs(
        role_arn=pulumi.Output.concat("arn:aws:iam::", account.id, ":role/", account.role_name)
    ),
    **config
)

vpc = awsx.ec2.Vpc("vpc", opts=pulumi.ResourceOptions(provider=provider))
```
I am using the following dependencies:

```
pulumi==3.48.0
pulumi-aws==5.23.0
pulumi-awsx==1.0.0
```

### Expected Behavior

I am expecting the VPC to be deployed into the newly created account.

### Actual Behavior

But pulumi preview throws this error:

```
Exception: Cannot read properties of undefined (reading 'length')
error: TypeError: Cannot read properties of undefined (reading 'length')
    at Vpc.getDefaultAzs (/snapshot/awsx/bin/ec2/vpc.js:184:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Vpc.initialize (/snapshot/awsx/bin/ec2/vpc.js:45:103)
```

### Output of `pulumi about`

CLI          
Version      3.48.0
Go Version   go1.19.2
Go Compiler  gc

Host     
OS       debian
Version  11.5
Arch     x86_64

### Additional context

When I comment out `assume_role `it works. It looks like it cannot resolve tha availability zones. When I add `availability_zone_names=["eu-central-1a", "eu-central-1b"]` to `awsx.ec2.Vpc` explicitly, it works as well.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by roothorp** [comment]
Hi @chris-stetter, thanks for the issue! I've raised this with the team so it can be prioritized and added to our work stack.

**Comment by chris-stetter** [comment]
Unfortunately, it is not.

**Comment by danielrbradley** [comment]
As a more robust workaround, you should be able to call [`getAvailabilityZones`](https://www.pulumi.com/registry/packages/aws/api-docs/getavailabilityzones/) yourself and pass the names from that result into `availability_zone_names`. This is what is happening internally in the provider. 

What's not currently clear is why the provider currently gets back an undefined set of names. We'll need to understand this further to be able to resolve the issue. It's possibly related to the use of an explicit provider. Do you also disable default providers?

**Comment by chris-stetter** [comment]
Yes I do.

**Comment by justinvp** [comment]
I can repro the same error with a TypeScript program (without involving MLCs or AWSx):

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const config: aws.ProviderArgs = {
    skipCredentialsValidation: true,
    skipMetadataApiCheck: false,
};

const orgProvider = new aws.Provider("org-provider", config);

const account = new aws.organizations.Account("account", {
    email: "test@example.com",
    roleName: "account-role",
}, {
    provider: orgProvider,
});

const provider = new aws.Provider("account-provider", {
    ...config,
    assumeRole: {
        roleArn: pulumi.interpolate `arn:aws:iam::${account.id}:role/${account.roleName}`,
    },
})

async function getDefaultAzs(provider: pulumi.ProviderResource): Promise<string[]> {
    const desiredCount = 3;
    const result = await aws.getAvailabilityZones(undefined, { provider });
    if (result.names.length < desiredCount) {
        throw new Error(`The configured region for this provider does not have at least ${desiredCount} Availability Zones.`);
    }
    return result.names.slice(0, desiredCount);
}

export const names = pulumi.output(getDefaultAzs(provider));
```

Running `pulumi up` results in the following error during preview:

```
    TypeError: Cannot read properties of undefined (reading 'length')
        at /Users/user/repro/index.ts:28:22
        at Generator.next (<anonymous>)
        at fulfilled (/Users/user/repro/index.ts:5:58)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by justinvp** [comment]
The reason the invoke returns an empty object is because of [this](https://github.com/pulumi/pulumi/blob/184e579e54554a4cb3f41f82cbeebd64f033315a/sdk/go/common/resource/plugin/provider_plugin.go#L1316-L1319):

```go
// If the provider is not fully configured, return an empty property map.
if !p.cfgknown {
	return resource.PropertyMap{}, nil, nil
}
```

During the first preview, the `organizations.Account` resource hasn't been created yet and the `account-provider` depends on its outputs, which will be unknown during preview, so it isn't configured, and returns an empty object when invoked.

I'm not yet sure if there's a way we could address this in the system.

One way to workaround this in a Pulumi program is to first create the `organizations.Account` and run `pulumi up`, and then add the code to create the provider and VPC and run that in a subsequent `pulumi up`.

**Comment by chris-stetter** [comment]
Unfortunately, this is not a solution that would work for me.

**Comment by danielrbradley** [comment]
A thought on alternative workarounds .. you could experiment with putting the whole provider and invoke within an apply callback using the result of the account. This would have the downside of hiding the operations within the apply from the preview (and would therefore not be compatible with plans) but might be a more feasible workaround than multiple runs? I can't test this myself as I don't have permissions to create AWS accounts from our testing environment.

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const config: aws.ProviderArgs = {
    skipCredentialsValidation: true,
    skipMetadataApiCheck: false,
};

const orgProvider = new aws.Provider("org-provider", config);

const account = new aws.organizations.Account("account", {
    email: "test@example.com",
    roleName: "account-role",
}, {
    provider: orgProvider,
});

const accountRoleArn = pulumi.interpolate`arn:aws:iam::${account.id}:role/${account.roleName}`;

async function getDefaultAzs(provider: pulumi.ProviderResource): Promise<string[]> {
    const desiredCount = 3;
    const result = await aws.getAvailabilityZones(undefined, { provider });
    if (result.names.length < desiredCount) {
        throw new Error(`The configured region for this provider does not have at least ${desiredCount} Availability Zones.`);
    }
    return result.names.slice(0, desiredCount);
}

export const names = accountRoleArn.apply((accountArn) => {
    const provider = new aws.Provider("account-provider", {
        ...config,
        assumeRole: {
            roleArn: accountArn,
        },
    });
    return getDefaultAzs(provider);
});
```

**Comment by corymhall** [comment]
Looks like this is still an issue.
